### ISSUE TITLE
Deploy Build Failure

### ISSUE THREAD

**Issue by tenoritaiga** [unfetter-discover/unfetter#1169]
Pulling down all of the repos unmodified from GitHub and doing a clean build using the `docker-compose.deploy.yml` file as described [here](https://github.com/unfetter-discover/unfetter/wiki/Unfetter-Build-Types-&-Run-Modes), the `unfetter-socket-server` component runs into this error:

```
[nodemon] starting `node --inspect=0.0.0.0:6555 --nolazy dist/server/server.js`
Debugger listening on ws://0.0.0.0:6555/4d89bb50-79c8-4530-883d-92a3b7f55257
For help, see: https://nodejs.org/en/docs/inspector
fs.js:126
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:614:3)
    at tryReadSync (fs.js:454:20)
    at Object.fs.readFileSync (fs.js:495:19)
    at Object.<anonymous> (/usr/share/unfetter-socket-server/dist/models/CONFIG.js:13:32)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/share/unfetter-socket-server/dist/middleware/jwtVerify.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
[nodemon] app crashed - waiting for file changes before starting...
```

The containers for the application start, but the user interface is not accessible.

**Comment by infosec-alchemist** [comment]
Hi, sorry we missed this one.  WE just did an update to Unfetter.  Can you try it with the latest?

**Comment by tenoritaiga** [comment]
Pulling the latest release from master, this appears to have been resolved. No longer seeing the error with either the deploy or development yml files. Thanks.

**Comment by infosec-alchemist** [comment]
Awesome.  thanks for the input
