### ISSUE TITLE
unfetter-dev doesn't seem to work for everyone

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#1223]
There appears to be a case where the unfetter-dev doesn't build the code properly.  Error is

```
Unable to start API:  { Error: ENOENT: no such file or directory, open '/etc/pki/tls/certs/server.key'
    at Object.fs.openSync (fs.js:559:3)
    at Object.fs.readFileSync (fs.js:465:33)
    at Promise (/usr/share/unfetter-discover-api/api/server/serverinit.js:44:21)
    at new Promise (<anonymous>)
    at module.exports (/usr/share/unfetter-discover-api/api/server/serverinit.js:39:24)
    at startServices (/usr/share/unfetter-discover-api/api/server/server.js:11:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/etc/pki/tls/certs/server.key' }
```

Likely a problem with creating the cert files.

Try building from a completely clean state with a newly checked out project

**Comment by infosec-alchemist** [comment]
A couple of problems were occurring
- [ ] Cert files were being created in a sub directory of the volume.  But this caused problems when building mapping the named volume to the api
- [ ] The private-config volume was being created, but the file was not being copied to it
- [ ] There was an error in the backup directory
