### ISSUE TITLE
NPM Test finds error in EADDRINUSE

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-discover/unfetter#279]
When running NPM test, the following error is found.  Needs to be resolved to support testing

1)  Uncaught error outside test suite:
     Uncaught Error: listen EADDRINUSE :::3000
      at Object.exports._errnoException (util.js:1050:11)
      at exports._exceptionWithHostPort (util.js:1073:20)
      at Server.setupListenHandle [as _listen2] (net.js:1259:14)
      at listenInCluster (net.js:1307:12)
      at Server.listen (net.js:1406:7)
      at Function.listen (node_modules/express/lib/application.js:618:24)
      at SwaggerExpress.create (app.js:41:7)
      at node_modules/swagger-express-mw/lib/index.js:32:5
      at node_modules/swagger-node-runner/index.js:179:5
      at node_modules/swagger-node-runner/node_modules/swagger-tools/index.js:84:7
      at cbWrapper (node_modules/swagger-node-runner/node_modules/swagger-tools/lib/specs.js:1035:5)
      at validateSwagger2_0 (node_modules/swagger-node-runner/node_modules/swagger-tools/lib/specs.js:1030:3)
      at validateSemantically (node_modules/swagger-node-runner/node_modules/swagger-tools/lib/specs.js:1040:5)
      at node_modules/swagger-node-runner/node_modules/swagger-tools/lib/specs.js:1233:7
      at node_modules/swagger-node-runner/node_modules/swagger-tools/lib/specs.js:1073:29
      at node_modules/swagger-node-runner/node_modules/swagger-tools/lib/specs.js:719:12

**Comment by j987987** [comment]
This should no longer be an issue, closing it.
