### ISSUE TITLE
docker-compose error: pull access denied for unfetter/cti-stix-store

### ISSUE THREAD

**Issue by sbehrens** [unfetter-discover/unfetter#659]
Full trace below:

```
docker-compose -f docker-compose.virtualbox.yml up
Cloning into 'unfetter'...
remote: Counting objects: 1173, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 1173 (delta 0), reused 1 (delta 0), pack-reused 1167
Receiving objects: 100% (1173/1173), 125.57 MiB | 9.90 MiB/s, done.
Resolving deltas: 100% (536/536), done.
Checking connectivity... done.
Creating network "unfetter_default" with the default driver
Pulling cti-stix-store-repository (mongo:3.4.1)...
3.4.1: Pulling from library/mongo
5040bd298390: Pull complete
ef697e8d464e: Pull complete
67d7bf010c40: Pull complete
bb0b4f23ca2d: Pull complete
8efff42d23e5: Pull complete
11dec5aa0089: Pull complete
e76feb0ad656: Pull complete
5e1dcc6263a9: Pull complete
2855a823db09: Pull complete
Digest: sha256:aff0c497cff4f116583b99b21775a8844a17bcf5c69f7f3f6028013bf0d6c00c
Status: Downloaded newer image for mongo:3.4.1
Pulling cti-stix-store (unfetter/cti-stix-store:latest)...
ERROR: pull access denied for unfetter/cti-stix-store, repository does not exist or may require 'docker login'
```

**Comment by mushinlogit** [comment]
Hello [unfetter/cti-stix-store](https://github.com/unfetter-discover/DEPRECIATED-cti-stix-store) is deprecated and has been moved to [unfetter/unfetter-store](https://github.com/unfetter-discover/unfetter-store).  Have you tried the [Case 1 or Case 2](https://github.com/unfetter-discover/unfetter) install instructions?

**Comment by sbehrens** [comment]
Hi,

I tried case 1 first, and that was the exception.  I also tried Case 2 and got a whole different slew of bugs, part of the trace is below:

```
unfetter-discover-api-explorer    |
unfetter-discover-api-explorer    | > unfetter-discover-api@0.3.3-s swaggerdev /usr/share/unfetter-discover-api
unfetter-discover-api-explorer    | > multi-file-swagger multifile-remote.yaml > api/swagger/swagger-remote.json && json2yaml ./api/swagger/swagger-remote.json > ./api/swagger/swagger-remote.yaml && swagger validate ./api/swagger/swagger.yaml && nodemon --watch ./api --ignore 'api/swagger/swagger*.*' -e js,yaml,json,yml app-editor.js
cti-stix-store-repository         | 2018-01-12T16:05:25.509+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3474M,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
unfetter-discover-api-explorer    |
unfetter-discover-openssl         | ..+++
unfetter-discover-api             |
unfetter-ui                       | npm ERR!     /root/.npm/_logs/2018-01-12T16_05_26_572Z-debug.log
cti-stix-store-repository         | 2018-01-12T16:05:25.595+0000 I CONTROL  [initandlisten]
unfetter-discover-api             | > unfetter-discover-api@0.3.3-s debugdev /usr/share/unfetter-discover-api
unfetter-ctf-ingest               |
cti-stix-store-repository         | 2018-01-12T16:05:25.595+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
unfetter-ctf-ingest               | > unfetter-ctf-ingest@0.3.3 start /usr/share/unfetter-ctf-ingest
unfetter-discover-api             | > npm run compileswagger && nodemon --inspect=0.0.0.0:5555 --watch ./api --ignore 'api/swagger/swagger*.*' -e js,yaml,json,yml api/server/server.js
cti-stix-store-repository         | 2018-01-12T16:05:25.595+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
unfetter-ctf-ingest               | > npm run build && node dist/app.js
unfetter-discover-api             |
cti-stix-store-repository         | 2018-01-12T16:05:25.595+0000 I CONTROL  [initandlisten]
unfetter-ctf-ingest               |
unfetter-discover-api             |
unfetter-discover-api-explorer    | { Error: ENOENT: no such file or directory, open './api/swagger/swagger.yaml'
cti-stix-store-repository         | 2018-01-12T16:05:25.614+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
unfetter-ctf-ingest               |
unfetter-discover-api             | > unfetter-discover-api@0.3.3-s compileswagger /usr/share/unfetter-discover-api
unfetter-discover-api-explorer    |     at Object.fs.openSync (fs.js:663:18)
cti-stix-store-repository         | 2018-01-12T16:05:25.625+0000 I INDEX    [initandlisten] build index on: admin.system.version properties: { v: 2, key: { version: 1 }, name: "incompatible_with_version_32", ns: "admin.system.version" }
unfetter-ctf-ingest               | > unfetter-ctf-ingest@0.3.3 build /usr/share/unfetter-ctf-ingest
unfetter-discover-api             | > multi-file-swagger multifile.yaml > api/swagger/swagger.json && json2yaml ./api/swagger/swagger.json > ./api/swagger/swagger.yaml && swagger validate ./api/swagger/swagger.yaml
unfetter-discover-api-explorer    |     at Object.fs.readFileSync (fs.js:568:33)
cti-stix-store-repository         | 2018-01-12T16:05:25.625+0000 I INDEX    [initandlisten] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
unfetter-ctf-ingest               | > tsc -v && mkdir -p ./dist/api/swagger && npm run copy:swagger && tsc -p . --outDir ./dist || exit 0
unfetter-discover-api             |
unfetter-discover-api-explorer    |     at Command.validate (/usr/local/lib/node_modules/swagger/lib/commands/commands.js:79:19)
unfetter-ctf-ingest               |
unfetter-discover-api-explorer    |     at Command.<anonymous> (/usr/local/lib/node_modules/swagger/lib/util/cli.js:167:27)
unfetter-ctf-ingest               | Version 2.6.2
unfetter-discover-api-explorer    |     at Command.listener (/usr/local/lib/node_modules/swagger/node_modules/commander/index.js:315:8)
unfetter-ctf-ingest               |
cti-stix-store-repository         | 2018-01-12T16:05:25.628+0000 I INDEX    [initandlisten] build index done.  scanned 0 total records. 0 secs
unfetter-discover-api-explorer    |     at Command.emit (events.js:159:13)
cti-stix-store-repository         | 2018-01-12T16:05:25.630+0000 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 3.4
unfetter-ctf-ingest               | > unfetter-ctf-ingest@0.3.3 copy:swagger /usr/share/unfetter-ctf-ingest
unfetter-discover-api-explorer    |     at Command.parseArgs (/usr/local/lib/node_modules/swagger/node_modules/commander/index.js:653:12)
unfetter-ctf-ingest               | > cp src/api/swagger/swagger.yaml dist/api/swagger
cti-stix-store-repository         | 2018-01-12T16:05:25.630+0000 I NETWORK  [thread1] waiting for connections on port 27017
unfetter-discover-api-explorer    |     at Command.parse (/usr/local/lib/node_modules/swagger/node_modules/commander/index.js:475:21)
unfetter-ctf-ingest               |
unfetter-discover-api-explorer    |     at Object.<anonymous> (/usr/local/lib/node_modules/swagger/bin/swagger.js:51:5)
unfetter-discover-api-explorer    |     at Module._compile (module.js:641:30)
unfetter-discover-api-explorer    |   errno: -2,
unfetter-discover-api-explorer    |   code: 'ENOENT',
unfetter-discover-api-explorer    |   syscall: 'open',
unfetter-discover-api-explorer    |   path: './api/swagger/swagger.yaml' }
unfetter-discover-api-explorer    | npm ERR! code ELIFECYCLE
unfetter-discover-api-explorer    | npm ERR! errno 1
unfetter-discover-api-explorer    | npm ERR! unfetter-discover-api@0.3.3-s swaggerdev: `multi-file-swagger multifile-remote.yaml > api/swagger/swagger-remote.json && json2yaml ./api/swagger/swagger-remote.json > ./api/swagger/swagger-remote.yaml && swagger validate ./api/swagger/swagger.yaml && nodemon --watch ./api --ignore 'api/swagger/swagger*.*' -e js,yaml,json,yml app-editor.js`
unfetter-discover-openssl         | ..............................+++
unfetter-discover-api-explorer    | npm ERR! Exit status 1
unfetter-discover-openssl         | writing new private key to '/tmp/certs/server.key'
unfetter-discover-openssl         | -----
unfetter-discover-api-explorer    | npm ERR!
unfetter-discover-api-explorer    | npm ERR! Failed at the unfetter-discover-api@0.3.3-s swaggerdev script.
unfetter-discover-api-explorer    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
unfetter-discover-api-explorer    |
unfetter-discover-api-explorer    | npm ERR! A complete log of this run can be found in:
unfetter-discover-api-explorer    | npm ERR!     /root/.npm/_logs/2018-01-12T16_05_29_263Z-debug.log
unfetter-ui exited with code 1
unfetter-discover-openssl exited with code 0
unfetter-discover-api-explorer exited with code 1
unfetter-discover-gateway         | 2018/01/12 16:05:30 [emerg] 1#1: host not found in upstream "unfetter-discover-api-explorer" in /etc/nginx/conf.d/default.conf:17
unfetter-discover-gateway         | nginx: [emerg] host not found in upstream "unfetter-discover-api-explorer" in /etc/nginx/conf.d/default.conf:17
unfetter-discover-api             |
unfetter-discover-api             | Project Warnings
unfetter-discover-api             | ----------------
unfetter-discover-api             | #/definitions/Count: Definition is defined but is not used: #/definitions/Count
unfetter-discover-api             | #/definitions/Question: Definition is defined but is not used: #/definitions/Question
unfetter-discover-api             | Results: 0 errors, 2 warnings
unfetter-discover-gateway exited with code 1
unfetter-discover-api             | [nodemon] 1.14.11
unfetter-discover-api             | [nodemon] to restart at any time, enter `rs`
unfetter-discover-api             | [nodemon] watching: /usr/share/unfetter-discover-api/api/**/*
unfetter-discover-api             | [nodemon] starting `node --inspect=0.0.0.0:5555 api/server/server.js`
unfetter-discover-api             | Debugger listening on ws://0.0.0.0:5555/c3a75ee1-c06f-4b5f-876b-9ea47c7832c4
unfetter-discover-api             | For help see https://nodejs.org/en/docs/inspector
unfetter-discover-processor       | (node:1) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
cti-stix-store-repository         | 2018-01-12T16:05:33.025+0000 I NETWORK  [thread1] connection accepted from 172.19.0.6:44132 #1 (1 connection now open)
cti-stix-store-repository         | 2018-01-12T16:05:33.031+0000 I NETWORK  [conn1] received client metadata from 172.19.0.6:44132 conn1: { driver: { name: "nodejs", version: "2.2.34" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.60-linuxkit-aufs" }, platform: "Node.js v9.2.1, LE, mongodb-core: 2.1.18" }
unfetter-discover-processor       | connected to mongodb
unfetter-discover-processor       | Adding Mitre data
unfetter-discover-processor       | Not using a proxy
unfetter-discover-api             | Please use unfetter-store/unfetter-utils/api_configuration_tool.py to create private-config.json
unfetter-discover-api             | [nodemon] app crashed - waiting for file changes before starting...
unfetter-discover-processor       | Processing the following STIX files:  [ '/tmp/examples/unfetter-stix/stix.json' ]
unfetter-discover-processor       | Processing the following enhanced STIX properties files:  [ '/tmp/examples/unfetter-db/stix-enhancements.json',
unfetter-discover-processor       |   '/tmp/examples/unfetter-db/stix-meta.json' ]
unfetter-discover-processor       | STIX property enhancement failed - Unable to find matching stix for:  undefined
unfetter-discover-processor       | STIX property enhancement failed - Unable to find matching stix for:  undefined
unfetter-discover-processor       | STIX property enhancement failed - Unable to find matching stix for:  undefined
unfetter-discover-processor       | STIX property enhancement failed - Unable to find matching stix for:  undefined
unfetter-discover-processor       | STIX property enhancement failed - Unable to find matching stix for:  undefined
unfetter-discover-processor       | STIX property enhancement failed - Unable to find matching stix for:  undefined
unfetter-discover-processor       | STIX property enhancement failed - Unable to find matching stix for:  undefined
unfetter-ctf-ingest               | node_modules/@types/papaparse/index.d.ts(17,29): error TS2304: Cannot find name 'File'.
unfetter-ctf-ingest               | node_modules/@types/papaparse/index.d.ts(19,31): error TS2304: Cannot find name 'ReadableStream'.
unfetter-ctf-ingest               | node_modules/@types/papaparse/index.d.ts(96,44): error TS2304: Cannot find name 'File'.
unfetter-ctf-ingest               | node_modules/@types/papaparse/index.d.ts(97,38): error TS2304: Cannot find name 'File'.
unfetter-ctf-ingest               | src/services/mongo-connection.service.ts(20,43): error TS2339: Property 'collection' does not exist on type 'MongoClient'.
unfetter-ctf-ingest               | src/services/mongo-connection.service.ts(22,45): error TS2339: Property 'collection' does not exist on type 'MongoClient'.
unfetter-discover-processor       | Processing the following configuration files:  [ '/tmp/examples/unfetter-db/config.json',
unfetter-discover-processor       |   '/tmp/examples/unfetter-db/translation-config.json' ]
unfetter-discover-processor       | (node:1) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
unfetter-ctf-ingest               | WARNING: No configurations found in configuration directory:/usr/share/unfetter-ctf-ingest/dist/config
unfetter-ctf-ingest               | WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
cti-stix-store-repository         | 2018-01-12T16:05:35.317+0000 I NETWORK  [thread1] connection accepted from 172.19.0.6:44136 #2 (2 connections now open)
cti-stix-store-repository         | 2018-01-12T16:05:35.327+0000 I NETWORK  [thread1] connection accepted from 172.19.0.6:44138 #3 (3 connections now open)
cti-stix-store-repository         | 2018-01-12T16:05:35.334+0000 I NETWORK  [thread1] connection accepted from 172.19.0.6:44140 #4 (4 connections now open)
cti-stix-store-repository         | 2018-01-12T16:05:35.336+0000 I NETWORK  [thread1] connection accepted from 172.19.0.6:44142 #5 (5 connections now open)
unfetter-discover-processor       | Error:  E11000 duplicate key error collection: stix.stix index: _id_ dup key: { : "report--44c023fa-dfcb-4334-9a44-ee9c096f96cf" }
cti-stix-store-repository         | 2018-01-12T16:05:35.589+0000 I -        [conn1] end connection 172.19.0.6:44132 (5 connections now open)
cti-stix-store-repository         | 2018-01-12T16:05:35.589+0000 I -        [conn5] end connection 172.19.0.6:44142 (4 connections now open)
cti-stix-store-repository         | 2018-01-12T16:05:35.590+0000 I -        [conn4] end connection 172.19.0.6:44140 (3 connections now open)
cti-stix-store-repository         | 2018-01-12T16:05:35.590+0000 I -        [conn2] end connection 172.19.0.6:44136 (5 connections now open)
cti-stix-store-repository         | 2018-01-12T16:05:35.590+0000 I -        [conn3] end connection 172.19.0.6:44138 (1 connection now open)
unfetter-discover-processor       | closed mongo connection
unfetter-discover-processor exited with code 1
```

**Comment by mushinlogit** [comment]
@sbehrens Sorry, it appears the compose file for Windows, `docker-compose.virtualbox.yml`, still references our old containers.  I can get back to you when this is fixed.  In the mean time the Mac and Linux steps should work as they are better tested and up to date.

**Comment by mushinlogit** [comment]
relates to unfetter-discover/unfetter#660

**Comment by mushinlogit** [comment]
pointed @sbehrens to the correct yml file and unfetter came up

**Comment by Genxint** [comment]
Hi - I am seeing the same error.  If there is something I can do to help or test, please let me know as I am happy to help and contribute where possible. <br><br>
  
![image](https://user-images.githubusercontent.com/35938005/40461260-72ea543c-5ed8-11e8-9205-784683107857.png)
