### ISSUE TITLE
Mongoose / Mongo Errors

### ISSUE THREAD

**Issue by zacoker** [unfetter-discover/unfetter#740]
$ docker-compose -f docker-compose.yml up
Pulling unfetter-discover-processor (unfetter/unfetter-discover-processor:0.3.4)...
0.3.4: Pulling from unfetter/unfetter-discover-processor
Digest: sha256:75eb5e43200bdbdc18cdb77f9425f334ac9ac22fa2e06b1dc50d75450c148a02
Status: Downloaded newer image for unfetter/unfetter-discover-processor:0.3.4
Pulling unfetter-discover-openssl (svagi/openssl:latest)...
latest: Pulling from svagi/openssl
6c123565ed5e: Pull complete
9b2675d39e56: Pull complete
Digest: sha256:a95ec4bb2610aab1b7d2469be1ca48fdf11c6bc213d2103a052de481da7e2803
Status: Downloaded newer image for svagi/openssl:latest
Pulling unfetter-discover-api (unfetter/unfetter-discover-api:0.3.4)...
0.3.4: Pulling from unfetter/unfetter-discover-api
Digest: sha256:f312b996118154c246fee164d27cb09f403bdc4614d57c1945afaf7c02765449
Status: Downloaded newer image for unfetter/unfetter-discover-api:0.3.4
Pulling unfetter-ctf-ingest (unfetter/unfetter-ctf-ingest:0.3.4)...
0.3.4: Pulling from unfetter/unfetter-ctf-ingest
Digest: sha256:f718d2be41b140f4d2932656eec0136bd790044d0b8248e440b645be28a582d1
Status: Downloaded newer image for unfetter/unfetter-ctf-ingest:0.3.4
Pulling unfetter-ui (unfetter/unfetter-ui:0.3.4)...
0.3.4: Pulling from unfetter/unfetter-ui
Digest: sha256:4345c9f66ff55efd8138bafcd0c68cd182ecf447c371a3275d309126962df08f
Status: Downloaded newer image for unfetter/unfetter-ui:0.3.4
Pulling unfetter-discover-gateway (nginx:1.13.5-alpine)...
1.13.5-alpine: Pulling from library/nginx
Creating unfetter-discover-openssl ... done
Creating cti-stix-store-repository ... done
049763556f13: Pull complete
555a8317e22d: Pull complete
Creating unfetter-discover-api ... done
Creating unfetter-ctf-ingest ... done
Creating unfetter-discover-gateway ... done
Creating unfetter-discover-openssl ...
Creating unfetter-ui ...
Creating unfetter-discover-api-explorer ...
Creating unfetter-discover-api ...
Creating unfetter-discover-processor ...
Creating unfetter-ctf-ingest ...
Creating unfetter-discover-gateway ...
Attaching to unfetter-discover-openssl, cti-stix-store-repository, unfetter-ui, unfetter-discover-api-explorer, unfetter-discover-processor, unfetter-discover-api, unfetter-ctf-ingest, unfetter-discover-gateway
unfetter-discover-openssl         | Generating a 2048 bit RSA private key
cti-stix-store-repository         | 2018-02-16T15:25:58.597+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=12900befd4b0
cti-stix-store-repository         | 2018-02-16T15:25:58.603+0000 I CONTROL  [initandlisten] db version v3.4.1
cti-stix-store-repository         | 2018-02-16T15:25:58.603+0000 I CONTROL  [initandlisten] git version: 5e103c4f5583e2566a45d740225dc250baacfbd7
cti-stix-store-repository         | 2018-02-16T15:25:58.603+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
cti-stix-store-repository         | 2018-02-16T15:25:58.603+0000 I CONTROL  [initandlisten] allocator: tcmalloc
cti-stix-store-repository         | 2018-02-16T15:25:58.603+0000 I CONTROL  [initandlisten] modules: none
unfetter-discover-openssl         | ...........+++
cti-stix-store-repository         | 2018-02-16T15:25:58.603+0000 I CONTROL  [initandlisten] build environment:
cti-stix-store-repository         | 2018-02-16T15:25:58.603+0000 I CONTROL  [initandlisten]     distmod: debian81
unfetter-ui                       | npm ERR! missing script: server:dev:alt
cti-stix-store-repository         | 2018-02-16T15:25:58.603+0000 I CONTROL  [initandlisten]     distarch: x86_64
cti-stix-store-repository         | 2018-02-16T15:25:58.603+0000 I CONTROL  [initandlisten]     target_arch: x86_64
cti-stix-store-repository         | 2018-02-16T15:25:58.603+0000 I CONTROL  [initandlisten] options: {}
unfetter-ui                       |
unfetter-ui                       | npm ERR! A complete log of this run can be found in:
cti-stix-store-repository         | 2018-02-16T15:25:58.669+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=256M,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
unfetter-ui                       | npm ERR!     /root/.npm/_logs/2018-02-16T15_26_22_118Z-debug.log
cti-stix-store-repository         | 2018-02-16T15:25:58.840+0000 E STORAGE  [initandlisten] WiredTiger error (1) [1518794758:840262][1:0x7fa7ee33bcc0], connection: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted
cti-stix-store-repository         | 2018-02-16T15:25:58.847+0000 I -        [initandlisten] Assertion: 28595:1: Operation not permitted src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp 267
cti-stix-store-repository         | 2018-02-16T15:25:58.849+0000 I STORAGE  [initandlisten] exception in initAndListen: 28595 1: Operation not permitted, terminating
cti-stix-store-repository         | 2018-02-16T15:25:58.849+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
cti-stix-store-repository         | 2018-02-16T15:25:58.849+0000 I NETWORK  [initandlisten] removing socket file: /tmp/mongodb-27017.sock
cti-stix-store-repository         | 2018-02-16T15:25:58.850+0000 I NETWORK  [initandlisten] shutdown: going to flush diaglog...
cti-stix-store-repository         | 2018-02-16T15:25:58.850+0000 I CONTROL  [initandlisten] now exiting
cti-stix-store-repository         | 2018-02-16T15:25:58.850+0000 I CONTROL  [initandlisten] shutting down with code:100
unfetter-discover-openssl         | ...........................................+++
unfetter-discover-openssl         | writing new private key to '/tmp/certs/server.key'
unfetter-discover-openssl         | -----
unfetter-discover-openssl exited with code 0
cti-stix-store-repository exited with code 100
unfetter-discover-gateway         | 2018/02/16 15:26:22 [emerg] 1#1: open() "/etc/nginx/./conf.d.extra/ssl-server.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:10
unfetter-discover-gateway         | nginx: [emerg] open() "/etc/nginx/./conf.d.extra/ssl-server.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:10
unfetter-ui exited with code 1
unfetter-discover-gateway exited with code 1
unfetter-discover-api             |
unfetter-discover-api             | > unfetter-discover-api@0.3.4 start /usr/share/unfetter-discover-api
unfetter-discover-api             | > npm run compileswagger && node api/server/server.js
unfetter-discover-api             |
unfetter-ctf-ingest               |
unfetter-ctf-ingest               | > unfetter-ctf-ingest@0.3.4 start /usr/share/unfetter-ctf-ingest
unfetter-ctf-ingest               | > npm run build && node dist/app.js
unfetter-ctf-ingest               |
unfetter-ctf-ingest               |
unfetter-ctf-ingest               | > unfetter-ctf-ingest@0.3.4 build /usr/share/unfetter-ctf-ingest
unfetter-ctf-ingest               | > tsc -v && mkdir -p ./dist/api/swagger && npm run copy:swagger && tsc -p . --outDir ./dist || exit 0
unfetter-ctf-ingest               |
unfetter-ctf-ingest               | Version 2.6.2
unfetter-discover-processor       | (node:1) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-api-explorer    |
unfetter-discover-api-explorer    | > unfetter-discover-api@0.3.4 swagger-editor /usr/share/unfetter-discover-api
unfetter-discover-api-explorer    | > multi-file-swagger multifile-remote.yaml > api/swagger/swagger-remote.json && json2yaml ./api/swagger/swagger-remote.json > ./api/swagger/swagger-remote.yaml && node app-editor.js
unfetter-discover-api-explorer    |
unfetter-discover-api-explorer    | Your server is listening on port 8080 (http://localhost:8080)
unfetter-discover-api             |
unfetter-discover-api             | > unfetter-discover-api@0.3.4 compileswagger /usr/share/unfetter-discover-api
unfetter-discover-api             | > multi-file-swagger multifile.yaml > api/swagger/swagger.json && json2yaml ./api/swagger/swagger.json > ./api/swagger/swagger.yaml && swagger validate ./api/swagger/swagger.yaml
unfetter-discover-api             |
unfetter-discover-api             |
unfetter-discover-api             | Project Warnings
unfetter-discover-api             | ----------------
unfetter-discover-api             | #/definitions/Count: Definition is defined but is not used: #/definitions/Count
unfetter-discover-api             | #/definitions/Question: Definition is defined but is not used: #/definitions/Question
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-api             | Results: 0 errors, 2 warnings
unfetter-discover-api             | (node:52) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-ctf-ingest               |
unfetter-ctf-ingest               | > unfetter-ctf-ingest@0.3.4 copy:swagger /usr/share/unfetter-ctf-ingest
unfetter-ctf-ingest               | > cp src/api/swagger/swagger.yaml dist/api/swagger
unfetter-ctf-ingest               |
unfetter-ctf-ingest               | node_modules/@types/papaparse/index.d.ts(17,29): error TS2304: Cannot find name 'File'.
unfetter-ctf-ingest               | node_modules/@types/papaparse/index.d.ts(19,31): error TS2304: Cannot find name 'ReadableStream'.
unfetter-ctf-ingest               | node_modules/@types/papaparse/index.d.ts(96,44): error TS2304: Cannot find name 'File'.
unfetter-ctf-ingest               | node_modules/@types/papaparse/index.d.ts(97,38): error TS2304: Cannot find name 'File'.
unfetter-ctf-ingest               | src/services/mongo-connection.service.ts(20,43): error TS2339: Property 'collection' does not exist on type 'MongoClient'.
unfetter-discover-api             | Listening on port 3000
unfetter-discover-api             | disconnected from mongodb
unfetter-discover-api             | connection error: { MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-api             |     at Pool.<anonymous> (/usr/share/unfetter-discover-api/node_modules/mongodb-core/lib/topologies/server.js:336:35)
unfetter-discover-api             |     at Pool.emit (events.js:159:13)
unfetter-discover-api             |     at Connection.<anonymous> (/usr/share/unfetter-discover-api/node_modules/mongodb-core/lib/connection/pool.js:280:12)
unfetter-discover-api             |     at Object.onceWrapper (events.js:254:19)
unfetter-discover-api             |     at Connection.emit (events.js:159:13)
unfetter-discover-api             |     at Socket.<anonymous> (/usr/share/unfetter-discover-api/node_modules/mongodb-core/lib/connection/connection.js:189:49)
unfetter-discover-api             |     at Object.onceWrapper (events.js:254:19)
unfetter-discover-api             |     at Socket.emit (events.js:159:13)
unfetter-discover-api             |     at emitErrorNT (internal/streams/destroy.js:64:8)
unfetter-discover-api             |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
unfetter-discover-api             |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
unfetter-discover-api             |   name: 'MongoError',
unfetter-discover-api             |   message: 'failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]' }
unfetter-discover-api             | (node:52) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-ctf-ingest               | src/services/mongo-connection.service.ts(22,45): error TS2339: Property 'collection' does not exist on type 'MongoClient'.
unfetter-ctf-ingest               | WARNING: No configurations found in configuration directory:/usr/share/unfetter-ctf-ingest/dist/config
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-processor       | Maximum number of connection attempts exceeded. Terminating program.
unfetter-discover-processor exited with code 1

**Comment by infosec-alchemist** [comment]
We just uploaded this version and found a problem in the build. @mushinlogit  is fixing it now and will let you know if we think we have it working

**Comment by mushinlogit** [comment]
@zacoker @infosec-alchemist sorry you are seeing errors. Looking at the logs, I believe there are two errors.

1. A configuration error, which will be fixed and pushed today. See,
```
unfetter-discover-gateway | 2018/02/16 15:26:22 [emerg] 1#1: open() "/etc/nginx/./conf.d.extra/ssl-server.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:10
unfetter-discover-gateway | nginx: [emerg] open() "/etc/nginx/./conf.d.extra/ssl-server.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:10
```
Stay tuned for a new pushed image in dockerhub to fix problem 1.  `https://hub.docker.com/u/unfetter/`

2. A mongo error, which we may have to work through. See,
```
cti-stix-store-repository | 2018-02-16T15:25:58.840+0000 E STORAGE [initandlisten] WiredTiger error (1) [1518794758:840262][1:0x7fa7ee33bcc0], connection: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted
...
unfetter-discover-processor | Maximum number of connection attempts exceeded. Terminating program.
```

@zacoker can you try the following Mongo and Docker comands?

1. First run just mongo
```
docker run -p 27017:27017 --name mongo_test -d mongo
```

2. Then run Mongo with mapped volume on your system. Replace `//c/Users/usrname/mongo_test` with a directory on your system.
```
docker run -p 27017:27017 --name mongo_test -v //c/Users/usrname/mongo_test:/data/db -d mongo
```
Does the second command give an `WiredTiger.wt: handle-open: open: Operation not permitted` error?

**Comment by mushinlogit** [comment]
@zacoker @infosec-alchemist May concern with the `Operation not permitted` error is with Mongo and Windows.  See, `https://github.com/docker-library/mongo/issues/74`

**Comment by zacoker** [comment]
1. Went fine:

```
$ docker run -p 27017:27017 --name mongo_test -d mongo
Unable to find image 'mongo:latest' locally
latest: Pulling from library/mongo
d2ca7eff5948: Pull complete
ebb958661291: Pull complete
cdfa71d101a9: Pull complete
88a286579fc2: Pull complete
9441b8e1ae36: Pull complete
0e6fe40bb4bd: Pull complete
ace74471951d: Pull complete
ddaafdd39b2a: Pull complete
d59a4258bd73: Pull complete
29f0c7020f3a: Pull complete
Digest: sha256:5556a788263cf8326897f2f58e63e970103fa06aa6bb15c2ffca18e374aa84c6
Status: Downloaded newer image for mongo:latest
545b3d274af5600228b477f5a679223765c7b34ae033a55059507fffd1364c8a
```

2. Had to rename mongo_test to run:

```
zcoker@XXXXXXXX MINGW64 ~/Projects/Unfetter-Discover/unfetter (master)
$ docker run -p 27017:27017 --name mongo_test -v ~Projects/Unfetter-Discover/mongo_test:/data/db -d mongo
C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: Conflict. The container name "/mongo_test" is already in use by container "545b3d274af5600228b477f5a679223765c7b34ae033a55059507fffd1364c8a". You have to remove (or rename) that container to be able to reuse that name.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.
```

```
zcoker@coker-open MINGW64 ~/Projects/Unfetter-Discover/unfetter (master)
$ docker run -p 27017:27017 --name mongo_test3 -v //c/Users/zcoker/Projects/Unfetter-Discover/mongo_test3:/data/db -d mongo
56c5fff29b747fecbccdeaabc0e8d154b3fcf7657ee6e27d1deb738bdc1ce873
```

```
zcoker@XXXXXXXX MINGW64 ~/Projects/Unfetter-Discover/unfetter (master)
Creating unfetter-discover-api ... done
Creating unfetter-ctf-ingest ... done
Creating unfetter-discover-gateway ... done
Creating unfetter-discover-openssl ...
Creating unfetter-discover-processor ...
Creating unfetter-discover-api-explorer ...
Creating unfetter-ui ...
Creating unfetter-discover-api ...
Creating unfetter-ctf-ingest ...
Creating unfetter-discover-gateway ...
Attaching to cti-stix-store-repository, unfetter-discover-openssl, unfetter-discover-processor, unfetter-ui, unfetter-discover-api-explorer, unfetter-discover-api, unfetter-ctf-ingest, unfetter-discover-gateway
cti-stix-store-repository         | 2018-02-16T18:37:52.067+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=9bc0ac1951f8
unfetter-discover-openssl         | Generating a 2048 bit RSA private key
unfetter-discover-processor       | (node:1) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
cti-stix-store-repository         | 2018-02-16T18:37:52.073+0000 I CONTROL  [initandlisten] db version v3.4.1
cti-stix-store-repository         | 2018-02-16T18:37:52.074+0000 I CONTROL  [initandlisten] git version: 5e103c4f5583e2566a45d740225dc250baacfbd7
cti-stix-store-repository         | 2018-02-16T18:37:52.074+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
cti-stix-store-repository         | 2018-02-16T18:37:52.074+0000 I CONTROL  [initandlisten] allocator: tcmalloc
cti-stix-store-repository         | 2018-02-16T18:37:52.074+0000 I CONTROL  [initandlisten] modules: none
cti-stix-store-repository         | 2018-02-16T18:37:52.074+0000 I CONTROL  [initandlisten] build environment:
cti-stix-store-repository         | 2018-02-16T18:37:52.074+0000 I CONTROL  [initandlisten]     distmod: debian81
unfetter-ui                       | npm ERR! missing script: server:dev:alt
cti-stix-store-repository         | 2018-02-16T18:37:52.074+0000 I CONTROL  [initandlisten]     distarch: x86_64
unfetter-discover-api             |
cti-stix-store-repository         | 2018-02-16T18:37:52.074+0000 I CONTROL  [initandlisten]     target_arch: x86_64
unfetter-discover-api             | > unfetter-discover-api@0.3.4 start /usr/share/unfetter-discover-api
cti-stix-store-repository         | 2018-02-16T18:37:52.075+0000 I CONTROL  [initandlisten] options: {}
unfetter-discover-api             | > npm run compileswagger && node api/server/server.js
unfetter-ui                       |
unfetter-discover-api             |
cti-stix-store-repository         | 2018-02-16T18:37:52.089+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=256M,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
unfetter-discover-gateway         | 2018/02/16 18:38:15 [emerg] 1#1: open() "/etc/nginx/./conf.d.extra/ssl-server.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:10
cti-stix-store-repository         | 2018-02-16T18:37:52.274+0000 E STORAGE  [initandlisten] WiredTiger error (17) [1518806272:274623][1:0x7fb8991ddcc0], connection: /data/db/WiredTiger.wt: handle-open: open: File exists
cti-stix-store-repository         | 2018-02-16T18:37:52.278+0000 E STORAGE  [initandlisten] WiredTiger error (26) [1518806272:278327][1:0x7fb8991ddcc0], connection: /data/db/WiredTiger.wt to /data/db/WiredTiger.wt.1: file-rename: rename: Text file busy
unfetter-ui                       | npm ERR! A complete log of this run can be found in:
cti-stix-store-repository         | 2018-02-16T18:37:52.316+0000 I -        [initandlisten] Assertion: 28595:26: Text file busy src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp 267
cti-stix-store-repository         | 2018-02-16T18:37:52.324+0000 I STORAGE  [initandlisten] exception in initAndListen: 28595 26: Text file busy, terminating
cti-stix-store-repository         | 2018-02-16T18:37:52.325+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
cti-stix-store-repository         | 2018-02-16T18:37:52.325+0000 I NETWORK  [initandlisten] removing socket file: /tmp/mongodb-27017.sock
cti-stix-store-repository         | 2018-02-16T18:37:52.325+0000 I NETWORK  [initandlisten] shutdown: going to flush diaglog...
cti-stix-store-repository         | 2018-02-16T18:37:52.325+0000 I CONTROL  [initandlisten] now exiting
cti-stix-store-repository         | 2018-02-16T18:37:52.325+0000 I CONTROL  [initandlisten] shutting down with code:100
unfetter-ui                       | npm ERR!     /root/.npm/_logs/2018-02-16T18_38_06_598Z-debug.log
unfetter-discover-openssl         | ..............................+++
unfetter-discover-openssl         | .................................................+++
unfetter-discover-openssl         | writing new private key to '/tmp/certs/server.key'
unfetter-discover-openssl         | -----
cti-stix-store-repository exited with code 100
unfetter-ui exited with code 1
unfetter-discover-openssl exited with code 0
unfetter-discover-gateway         | nginx: [emerg] open() "/etc/nginx/./conf.d.extra/ssl-server.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/default.conf:10
unfetter-ctf-ingest               |
unfetter-ctf-ingest               | > unfetter-ctf-ingest@0.3.4 start /usr/share/unfetter-ctf-ingest
unfetter-ctf-ingest               | > npm run build && node dist/app.js
unfetter-ctf-ingest               |
unfetter-discover-gateway exited with code 1
unfetter-ctf-ingest               |
unfetter-ctf-ingest               | > unfetter-ctf-ingest@0.3.4 build /usr/share/unfetter-ctf-ingest
unfetter-ctf-ingest               | > tsc -v && mkdir -p ./dist/api/swagger && npm run copy:swagger && tsc -p . --outDir ./dist || exit 0
unfetter-ctf-ingest               |
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-ctf-ingest               | Version 2.6.2
unfetter-discover-api-explorer    |
unfetter-discover-api-explorer    | > unfetter-discover-api@0.3.4 swagger-editor /usr/share/unfetter-discover-api
unfetter-discover-api-explorer    | > multi-file-swagger multifile-remote.yaml > api/swagger/swagger-remote.json && json2yaml ./api/swagger/swagger-remote.json > ./api/swagger/swagger-remote.yaml && node app-editor.js
unfetter-discover-api-explorer    |
unfetter-discover-api-explorer    | Your server is listening on port 8080 (http://localhost:8080)
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-api             |
unfetter-discover-api             | > unfetter-discover-api@0.3.4 compileswagger /usr/share/unfetter-discover-api
unfetter-discover-api             | > multi-file-swagger multifile.yaml > api/swagger/swagger.json && json2yaml ./api/swagger/swagger.json > ./api/swagger/swagger.yaml && swagger validate ./api/swagger/swagger.yaml
unfetter-discover-api             |
unfetter-discover-api             |
unfetter-discover-api             | Project Warnings
unfetter-discover-api             | ----------------
unfetter-discover-api             | #/definitions/Count: Definition is defined but is not used: #/definitions/Count
unfetter-discover-api             | #/definitions/Question: Definition is defined but is not used: #/definitions/Question
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-api             | Results: 0 errors, 2 warnings
unfetter-discover-api             | (node:52) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-api             | Listening on port 3000
unfetter-discover-api             | disconnected from mongodb
unfetter-discover-api             | connection error: { MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-api             |     at Pool.<anonymous> (/usr/share/unfetter-discover-api/node_modules/mongodb-core/lib/topologies/server.js:336:35)
unfetter-discover-api             |     at Pool.emit (events.js:159:13)
unfetter-discover-api             |     at Connection.<anonymous> (/usr/share/unfetter-discover-api/node_modules/mongodb-core/lib/connection/pool.js:280:12)
unfetter-discover-api             |     at Object.onceWrapper (events.js:254:19)
unfetter-discover-api             |     at Connection.emit (events.js:159:13)
unfetter-discover-api             |     at Socket.<anonymous> (/usr/share/unfetter-discover-api/node_modules/mongodb-core/lib/connection/connection.js:189:49)
unfetter-discover-api             |     at Object.onceWrapper (events.js:254:19)
unfetter-discover-api             |     at Socket.emit (events.js:159:13)
unfetter-discover-api             |     at emitErrorNT (internal/streams/destroy.js:64:8)
unfetter-discover-api             |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
unfetter-discover-api             |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
unfetter-discover-api             |   name: 'MongoError',
unfetter-discover-api             |   message: 'failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]' }
unfetter-discover-api             | (node:52) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-ctf-ingest               |
unfetter-ctf-ingest               | > unfetter-ctf-ingest@0.3.4 copy:swagger /usr/share/unfetter-ctf-ingest
unfetter-ctf-ingest               | > cp src/api/swagger/swagger.yaml dist/api/swagger
unfetter-ctf-ingest               |
unfetter-ctf-ingest               | node_modules/@types/papaparse/index.d.ts(17,29): error TS2304: Cannot find name 'File'.
unfetter-ctf-ingest               | node_modules/@types/papaparse/index.d.ts(19,31): error TS2304: Cannot find name 'ReadableStream'.
unfetter-ctf-ingest               | node_modules/@types/papaparse/index.d.ts(96,44): error TS2304: Cannot find name 'File'.
unfetter-ctf-ingest               | node_modules/@types/papaparse/index.d.ts(97,38): error TS2304: Cannot find name 'File'.
unfetter-ctf-ingest               | src/services/mongo-connection.service.ts(20,43): error TS2339: Property 'collection' does not exist on type 'MongoClient'.
unfetter-ctf-ingest               | src/services/mongo-connection.service.ts(22,45): error TS2339: Property 'collection' does not exist on type 'MongoClient'.
unfetter-ctf-ingest               | WARNING: No configurations found in configuration directory:/usr/share/unfetter-ctf-ingest/dist/config
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-processor       | Mongoose connection error: MongoError: failed to connect to server [repository:27017] on first connect [MongoError: getaddrinfo ENOTFOUND repository repository:27017]
unfetter-discover-processor       | Maximum number of connection attempts exceeded. Terminating program.
unfetter-discover-processor exited with code 1
```

**Comment by mushinlogit** [comment]
@zacoker I think you had an old master branch.  Can you delete that directory and repull?

```
mkdir unfetter-discover
cd unfetter-discover
git clone https://github.com/unfetter-discover/unfetter.git
cd unfetter
docker-compose up
```

**Comment by infosec-alchemist** [comment]
Closing.  @zacoker please reopen if you are still having trouble.
